version: "3"
services:
  mongodb:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d

  mongoku:
    image: huggingface/mongoku
    ports:
      - 3100:3100
    environment:
      MONGOKU_DEFAULT_HOST: mongodb://root:root@mongodb:27017/
